// Single source of truth for the sidebar's structure. Each entry is either:
//   { type: 'link', path, label }                         — a flat, directly navigable item
//   { type: 'dropdown', key, label, children: [{path,label}] } — a collapsible group (no own page)
export const sidebarNav = [
  { type: 'link', path: '/dashboard', label: 'Dashboard' },
  {
    type: 'dropdown',
    key: 'management',
    label: 'Management',
    children: [
      { path: '/management/client-management', label: 'Client Management' },
      { path: '/management/debtor-management', label: 'Debtor Management' },
      { path: '/management/file-management', label: 'File Management' },
      { path: '/management/closed-files', label: 'Closed Files' },
      { path: '/management/agent-management', label: 'Agent Management' },
    ],
  },
  { type: 'link', path: '/case-management', label: 'Case Management' },
  {
    type: 'dropdown',
    key: 'communication',
    label: 'Communication',
    children: [
      { path: '/communication/bulk-sms', label: 'Bulk SMS' },
      { path: '/communication/bulk-emails', label: 'Bulk Emails' },
      { path: '/communication/communication-channels', label: 'Communication Channels' },
      { path: '/communication/discounts-and-waivers', label: 'Discounts and Waivers' },
    ],
  },
  { type: 'link', path: '/contact-upload', label: 'Contact Upload' },
  {
    type: 'dropdown',
    key: 'payments',
    label: 'Payments',
    children: [
      { path: '/payments/payments', label: 'Payments' },
      { path: '/payments/commissions', label: 'Commissions' },
      { path: '/payments/ptp', label: 'PTP (Promise to Pay)' },
      { path: '/payments/non-confirmed-payments', label: 'Non-confirmed Payments' },
    ],
  },
  {
    type: 'dropdown',
    key: 'reports',
    label: 'Reports',
    children: [
      { path: '/reports/debtor-summary', label: 'Debtor Summary' },
      { path: '/reports/payment-performance', label: 'Payment Performance' },
      { path: '/reports/collector-performance', label: 'Collector Performance' },
      { path: '/reports/portfolio-performance', label: 'Portfolio Performance' },
      { path: '/reports/promise-to-pay', label: 'Promise To Pay' },
      { path: '/reports/aging-report', label: 'Aging Report' },
      { path: '/reports/dispute-management', label: 'Dispute Management' },
      { path: '/reports/recovery-rate', label: 'Recovery Rate' },
      { path: '/reports/goip-calls-report', label: 'GOIP Calls Report' },
      { path: '/reports/sms-report', label: 'SMS Report' },
      { path: '/reports/debtor-notes', label: 'Debtor Notes' },
      { path: '/reports/contact-attempt', label: 'Contact Attempt' },
    ],
  },
  {
    type: 'dropdown',
    key: 'settings',
    label: 'Settings',
    children: [
      { path: '/settings/commission-rates', label: 'Commission Rates' },
      { path: '/settings/debt-type', label: 'Debt Type' },
      { path: '/settings/debt-category', label: 'Debt Category' },
      { path: '/settings/client-type', label: 'Client Type' },
      { path: '/settings/debtor-upload-rules', label: 'Debtor Upload Rules' },
      { path: '/settings/currency', label: 'Currency' },
      { path: '/settings/payment-channels', label: 'Payment Channels' },
      { path: '/settings/closure-reason', label: 'Closure Reason' },
      { path: '/settings/template-variables', label: 'Template Variables' },
      { path: '/settings/case-priority', label: 'Case Priority' },
      { path: '/settings/agent-experience', label: 'Agent Experience' },
      { path: '/settings/agent-expertise', label: 'Agent Expertise' },
      { path: '/settings/client-agents', label: 'Client Agents' },
      { path: '/settings/workload-parameters', label: 'Workload Parameters' },
      { path: '/settings/contactability', label: 'Contactability' },
      { path: '/settings/contact-type', label: 'Contact Type' },
      { path: '/settings/contact-status', label: 'Contact Status' },
    ],
  },
  { type: 'link', path: '/system-configurations', label: 'System Configurations' },
];
